version: '3'
services:
  qna-rag-redis-server:
    image: qna-rag-redis:latest
    container_name: qna-rag-redis-server
    environment:
      - "REDIS_PORT=6379"
      - "EMBED_MODEL=BAAI/bge-base-en-v1.5"
      - "REDIS_SCHEMA=schema_dim_768.yml"
      - "HUGGINGFACEHUB_API_TOKEN=<update-your-hugging-face-token>"
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
    volumes:
      - ../redis:/ws 
      - ../test:/test
    network_mode: "host"
