version: '3'
services:
  qna-rag-redis-server:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
      dockerfile: Dockerfile
    image: intel/gen-ai-examples:qna-rag-redis-server
    container_name: qna-rag-redis-server
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - "REDIS_PORT=6379"
      - "EMBED_MODEL=BAAI/bge-base-en-v1.5"
      - "REDIS_SCHEMA=schema_dim_768.yml"
      - "HUGGINGFACEHUB_API_TOKEN=<update-your-hugging-face-token>"
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
    volumes:
      - ../redis:/ws 
      - ../test:/test
    network_mode: "host"
